version: "3" # composeファイルのバージョン
services: 
    app: # コンテナ名
        build: . # ビルドに使うDockerfileの場所
        command: /bin/sh -c "go run main.go"
        tty: true # コンテナの永続化s
        ports: # ホストOSのポートとコンテナのポートをつなげる 
            - "8080:8080"
        volumes:
            - ./app:/go/src/app # マウントディレクトリ
        depends_on: 
            - mysql

    mysql:
        build: ./mysql/    #Dockerfileからビルドすることを示す
        volumes:
          - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
        image: original_mysql_world # イメージの名前
        environment:
          - MYSQL_ROOT_USER=root
          - MYSQL_ROOT_PASSWORD=taitasu2 #コンテナ内のMySQLを起動する際のパスワードを設定
          - MYSQL_ROOT_HOST=% 
        ports: 
          - "3307:3306"



     