version: "3" # composeファイルのバージョン
services: 
    app: # コンテナ名
        build: .    # ビルドに使うDockerfileの場所
        command: /bin/sh -c "go run main.go"
        tty: true # コンテナの永続化s
        ports: # ホストOSのポートとコンテナのポートをつなげる。 左がホスト側
            - "8080:8080"
        volumes:
            - ./app:/go/src/app # マウントディレクトリ
        depends_on: 
            - mysql

    mysql:
        build: ./mysql/    #Dockerfileからビルドすることを示す
        volumes:
          - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
        image: original_mysql_world # イメージの名前
        environment:
          MYSQL_ROOT_PASSWORD: xxxx
          MYSQL_DATABASE: capsule
          TZ: 'Asia/Tokyo'
        ports:
          - "3307:3306"
        container_name: "mysql-container"




     