version: "3" # composeファイルのバージョン
services: 
    app: # コンテナ名
        build: . # ビルドに使うDockerfileの場所
        tty: true # コンテナの永続化s
        ports: # ホストOSのポートとコンテナのポートをつなげる 
            - "8080:8080"
        volumes:
            - ./app:/go/src/app # マウントディレクトリ
        depends_on: 
            - mysql

    mysql:
        build: ./mysql/
        volumes:
            # 初期データを投入するSQLが格納されているdir
            - ./mysql/init:/docker-entrypoint-initdb.d
            # 永続化するときにマウントするdir
            - ./mysql/data:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=taitasu2
        ports:
            - "3306:3306"